from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    b = p.chromium.launch()
    page = b.new_page(viewport={"width": 1440, "height": 900}, device_scale_factor=2)
    page.goto("https://muse-console-vladimirdeziegler-gmailcoms-projects.vercel.app")
    page.wait_for_timeout(2000)
    page.fill("textarea", "Hi, my name is Vlad. What is 5+5?")
    page.keyboard.press("Enter")
    page.wait_for_timeout(18000)
    page.fill("textarea", "What did I say my name was?")
    page.keyboard.press("Enter")
    page.wait_for_timeout(18000)
    page.fill("textarea", "And one AI headline from today, with a source.")
    page.keyboard.press("Enter")
    page.wait_for_timeout(25000)
    page.screenshot(path="repro-prod-followup.png", full_page=True)
    banner = page.locator(".err-banner")
    print("ERROR_BANNER:", banner.inner_text() if banner.count() else "(none)")
    print("assistant messages:", page.locator(".msg.assistant").count())
    b.close()
